version: "3.8"

volumes:
  db-data:
    name: db-data

services:
  kiwi-server:
    container_name: kiwi-server
    build: '.'
    restart: on-failure
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
    healthcheck:
      test: curl -f http://localhost:8000 || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      postgres-db:
        condition: service_healthy
  
  postgres-db:
    container_name: kiwi-db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgres/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 10s
      timeout: 3s
      retries: 3